### ISSUE TITLE
Nemo freezes PC when opening specific folder

### ISSUE THREAD

**Issue by Igloo7805** [linuxmint/nemo#3436]
### Distribution

Linux Mint 21.3 x86_64

### Package version

6.0.2

### Frequency

Always

### Bug description

When I try to access **sys/kernel/debug/dri/0** with Nemo my PC freezes instantly. This freeze is reproducable and happens every time I try to access this folder. I cant move the mouse or use the keyboard. 

I can access this folder with the terminal without any problems.

### Steps to reproduce

1.) in nemo navigate to sys/kernel/
2.) double click on /sys/kernel/debug folder
3.) enter credentials (twice) to get root access
4.) in nemo (now with root privileges) navigate to sys/kernel/debug/dri/
5.) when clicking on /0/ folder the whole system freezes

### Expected behavior

I would expect nemo to show the content of **sys/kernel/debug/dri/0** instead of freezing

### Additional information

No relevant entries in syslog or kern.log are made. 
No system reports available

GPU: 7900XT

```
Graphics:
  Device-1: AMD driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu
    resolution: 3840x2160~144Hz
  OpenGL: renderer: GFX1100 (gfx1100 LLVM 15.0.7 DRM 3.54 6.5.0-35-generic)
    v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.2
```
